# use containers
sudo: false

before_install:
  - gem install bundler

language: ruby
cache: bundler

rvm:
  - 2.2.3
  - 2.1.7
  - 2.0.0
  - 1.9.3
  - jruby-19mode
  - rbx-19mode

gemfile:
  - ci/Gemfile.rails32
  - ci/Gemfile.rails4
  - ci/Gemfile.rails41
  - ci/Gemfile.rails42

# Following the compatibility table at http://logfile.swobspace.net/blog/2015/01/01/Ruby-and-Rails.html, we can exclude these.
exclude:
  - rvm: 2.2.3
    gemfile:
      - ci/Gemfile.rails32
      - ci/Gemfile.rails40
      - ci/Gemfile.rails41
  - rvm: 2.1.7
    gemfile:
      - ci/Gemfile.rails32
      - ci/Gemfile.rails40
