# use containers
sudo: false

before_install:
  - gem install bundler

language: ruby
cache: bundler

rvm:
  - 2.4.1
  - 2.3.4
  - 2.2.7
  - 2.1.10
  - jruby-9.1.2.0
  - rbx-2

gemfile:
  - ci/Gemfile.rails42
  - ci/Gemfile.rails50

matrix:
  exclude:
    # Rails 5.0 needs Ruby > 2.2.2
    - rvm: 2.1.10
      gemfile: ci/Gemfile.rails50
